#!/usr/bin/ruby
#### INFO ######################################################################
# ahco (Automatic Handsfree Can Opener) - restore utility for Conserve backups.
# (*w) author: nixargh <nixargh@gmail.com>
$version = '0.0.1.0'
#### LICENSE ###################################################################
# ahco - restore utility for Conserve backups.
# Copyright (C) 2013  nixargh <nixargh@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/gpl.html.
#### SETTINGS ##################################################################
#### REQUIRE ###################################################################
require 'fileutils'
#### CLASES ####################################################################
class AHCO
  def initialize
    @lib_dir = '/usr/lib/ahco'
  end

  def load_libraries!
end
#### FUNCTIONS #################################################################
#### PROGRAM ###################################################################
